version: "3.4"

services:
  web:
    image: weteling.com
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    env_file:
      - .envrc
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - NODE_OPTIONS=--openssl-legacy-provider
        
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    volumes: 
      - ./volumes/db-data:/docker-entrypoint-initdb.d
