version: "3.4"

services:
  web:
    image: weteling.com
    build: .
    command: bundle exec rails s -b 0.0.0.0 -p 3000
    ports:
      - 3000:3000
    env_file:
      - .envrc
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./dbdump.sql:/docker-entrypoint-initdb.d/dbdump.sql

