version: 2
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/node:latest
        environment:
          NPM_TOKEN: this-is-fake
    steps:
      - checkout

      - run:
          name: Release
          command: |
            npm i
            npx semantic-release
